// src/App.vue
<script setup lang="ts">
import Header from '@/components/custom/Header.vue';
import Sidebar from '@/components/custom/Sidebar.vue';
import SidebarProvider from '@/components/ui/sidebar/SidebarProvider.vue';
import { RouterView } from 'vue-router';
</script>

<template>
  <SidebarProvider>
    <Sidebar></Sidebar>
    <main class="w-screen h-dvh">
      <Header></Header>
      <RouterView></RouterView>
    </main>
  </SidebarProvider>
</template>

// src/App.svelte
<script lang="ts">
  import Header from "$lib/components/custom/Header.svelte";
  import Main from "$lib/pages/Main.svelte";
  import { ModeWatcher } from "mode-watcher";
  import { Router, Route } from "svelte-routing";
</script>

<main class="dark:bg-gray-900 bg-indigo-50 w-screen h-dvh overflow-x-hidden">
  <Header />
  <Router>
    <Route path="/" component={Main} />
  </Router>
  <ModeWatcher />
</main>
